#!/bin/sh
set -eu

: "${REMOTEXAPP_RUNTIME:?}"
: "${REMOTEXAPP_CORE_DRIVER_DIR:?}"

REMOTEXAPP_SHUTDOWN_PID="$REMOTEXAPP_RUNTIME/firefox-esr-process.pid"
export REMOTEXAPP_SHUTDOWN_PID
exec "$REMOTEXAPP_CORE_DRIVER_DIR/window-close.sh"
